### ISSUE TITLE
Unhandled rejection Error: predict() must take an object where the keys are the named inputs of the model:

### ISSUE THREAD

**Issue by jose2007kj** [jhertzog/KerasPhone#2]
sir @jhertzog , i am getting following error,where i might be going wrong,(image is displayed bt.....its not showing any result,)..........sir i only did npm install,do i need to do any additional configrations

polyfills.js:1 GET file:///android_asset/assets/data/resnet50/resnet50.json net::ERR_FILE_NOT_FOUNDe @ polyfills.js:1t.scheduleTask @ polyfills.js:3e.scheduleMacroTask @ polyfills.js:3(anonymous function) @ polyfills.js:1send @ VM343:3(anonymous function) @ keras.js:4r._execute @ keras.js:32i._resolveFromExecutor @ keras.js:33i @ keras.js:33l.value @ keras.js:4(anonymous function) @ keras.js:4l.value @ keras.js:4t @ keras.js:4t.checkAndRunModel @ main.js:14(anonymous function) @ main.js:14t.invokeTask @ polyfills.js:3inner.inner.fork.onInvokeTask @ main.js:3t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at XMLHttpRequest.i.onerror (file:///android_asset/www/assets/keras.js:4:23486)
    at XMLHttpRequest.n [as _onerror] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
From previous event:
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22912)
    at file:///android_asset/www/assets/keras.js:4:22656
    at Array.map (native)
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22631)
    at new t (file:///android_asset/www/assets/keras.js:4:22286)
    at t.checkAndRunModel (file:///android_asset/www/build/main.js:14:20585)
    at file:///android_asset/www/build/main.js:14:22178
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at invoke (file:///android_asset/www/build/polyfills.js:3:15164)
Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at XMLHttpRequest.i.onerror (file:///android_asset/www/assets/keras.js:4:23486)
    at XMLHttpRequest.n [as _onerror] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
From previous event:
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22912)
    at file:///android_asset/www/assets/keras.js:4:22656
    at Array.map (native)
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22631)
    at new t (file:///android_asset/www/assets/keras.js:4:22286)
    at t.checkAndRunModel (file:///android_asset/www/build/main.js:14:20585)
    at file:///android_asset/www/build/main.js:14:22178
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at invoke (file:///android_asset/www/build/polyfills.js:3:15164)
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13373)
    at e.run (file:///android_asset/www/build/polyfills.js:3:10809)
    at file:///android_asset/www/build/polyfills.js:3:8911
keras.js:4 XMLHttpRequestProgressEvent {isTrusted: true, position: 0, totalSize: 0, lengthComputable: false, loaded: 0…}
main.js:14 done
keras.js:32 Unhandled rejection Error: predict() must take an object where the keys are the named inputs of the model: .
    at t.<anonymous> (file:///android_asset/www/assets/keras.js:4:28341)
    at o (file:///android_asset/www/assets/keras.js:44:2132)
    at s._invoke (file:///android_asset/www/assets/keras.js:44:3534)
    at s.t.(anonymous function) [as next] (file:///android_asset/www/assets/keras.js:44:2311)
From previous event:
    at t (file:///android_asset/www/assets/keras.js:4:28013)
    at t.runModel (file:///android_asset/www/build/main.js:14:21414)
    at file:///android_asset/www/build/main.js:14:20759
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
From previous event:
    at t.checkAndRunModel (file:///android_asset/www/build/main.js:14:20701)
    at file:///android_asset/www/build/main.js:14:22178
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at invoke (file:///android_asset/www/build/polyfills.js:3:15164)
polyfills.js:1 GET file:///android_asset/assets/data/resnet50/resnet50_metadata.json net::ERR_FILE_NOT_FOUNDe @ polyfills.js:1t.scheduleTask @ polyfills.js:3e.scheduleMacroTask @ polyfills.js:3(anonymous function) @ polyfills.js:1send @ VM343:3(anonymous function) @ keras.js:4r._execute @ keras.js:32i._resolveFromExecutor @ keras.js:33i @ keras.js:33l.value @ keras.js:4(anonymous function) @ keras.js:4l.value @ keras.js:4t @ keras.js:4t.checkAndRunModel @ main.js:14(anonymous function) @ main.js:14t.invokeTask @ polyfills.js:3inner.inner.fork.onInvokeTask @ main.js:3t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at XMLHttpRequest.i.onerror (file:///android_asset/www/assets/keras.js:4:23486)
    at XMLHttpRequest.n [as _onerror] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
From previous event:
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22912)
    at file:///android_asset/www/assets/keras.js:4:22656
    at Array.map (native)
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22631)
    at new t (file:///android_asset/www/assets/keras.js:4:22286)
    at t.checkAndRunModel (file:///android_asset/www/build/main.js:14:20585)
    at file:///android_asset/www/build/main.js:14:22178
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at invoke (file:///android_asset/www/build/polyfills.js:3:15164)
main.js:12 0
polyfills.js:1 GET file:///android_asset/assets/data/mnist_cnn/mnist_cnn.json net::ERR_FILE_NOT_FOUNDe @ polyfills.js:1t.scheduleTask @ polyfills.js:3e.scheduleMacroTask @ polyfills.js:3(anonymous function) @ polyfills.js:1send @ VM343:3(anonymous function) @ keras.js:4r._execute @ keras.js:32i._resolveFromExecutor @ keras.js:33i @ keras.js:33l.value @ keras.js:4(anonymous function) @ keras.js:4l.value @ keras.js:4t @ keras.js:4t @ main.js:12t @ main.js:35e.createInternal @ main.js:35t.create @ main.js:2t.create @ main.js:2e._viewInit @ main.js:8e._nextTrns @ main.js:8e._queueTrns @ main.js:8e._setPages @ main.js:8e.setRoot @ main.js:8t.openPage @ main.js:12e._handle_click_0_0 @ main.js:31(anonymous function) @ main.js:10(anonymous function) @ main.js:17t.invoke @ polyfills.js:3inner.inner.fork.onInvoke @ main.js:3t.invoke @ polyfills.js:3e.runGuarded @ polyfills.js:3t.runGuarded @ main.js:3s @ main.js:17t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at XMLHttpRequest.i.onerror (file:///android_asset/www/assets/keras.js:4:23486)
    at XMLHttpRequest.n [as _onerror] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
From previous event:
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22912)
    at file:///android_asset/www/assets/keras.js:4:22656
    at Array.map (native)
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22631)
    at new t (file:///android_asset/www/assets/keras.js:4:22286)
    at new t (file:///android_asset/www/build/main.js:12:13315)
    at new t (file:///android_asset/www/build/main.js:35:12930)
    at e.createInternal (file:///android_asset/www/build/main.js:35:13377)
    at e.t.create (file:///android_asset/www/build/main.js:2:7287)
    at t.create (file:///android_asset/www/build/main.js:2:4857)
    at e._viewInit (file:///android_asset/www/build/main.js:8:5217)
    at e._nextTrns (file:///android_asset/www/build/main.js:8:3336)
    at e._queueTrns (file:///android_asset/www/build/main.js:8:3111)
    at e._setPages (file:///android_asset/www/build/main.js:8:2230)
    at e.setRoot (file:///android_asset/www/build/main.js:8:2013)
    at t.openPage (file:///android_asset/www/build/main.js:12:1962)
    at e._handle_click_0_0 (file:///android_asset/www/build/main.js:31:28079)
    at file:///android_asset/www/build/main.js:10:19597
    at file:///android_asset/www/build/main.js:17:1516
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13373)
    at e.run (file:///android_asset/www/build/polyfills.js:3:10809)
    at file:///android_asset/www/build/polyfills.js:3:8911
keras.js:4 XMLHttpRequestProgressEvent {isTrusted: true, position: 0, totalSize: 0, lengthComputable: false, loaded: 0…}
main.js:12 undefined
polyfills.js:1 GET file:///android_asset/assets/data/mnist_cnn/mnist_cnn_metadata.json net::ERR_FILE_NOT_FOUNDe @ polyfills.js:1t.scheduleTask @ polyfills.js:3e.scheduleMacroTask @ polyfills.js:3(anonymous function) @ polyfills.js:1send @ VM343:3(anonymous function) @ keras.js:4r._execute @ keras.js:32i._resolveFromExecutor @ keras.js:33i @ keras.js:33l.value @ keras.js:4(anonymous function) @ keras.js:4l.value @ keras.js:4t @ keras.js:4t @ main.js:12t @ main.js:35e.createInternal @ main.js:35t.create @ main.js:2t.create @ main.js:2e._viewInit @ main.js:8e._nextTrns @ main.js:8e._queueTrns @ main.js:8e._setPages @ main.js:8e.setRoot @ main.js:8t.openPage @ main.js:12e._handle_click_0_0 @ main.js:31(anonymous function) @ main.js:10(anonymous function) @ main.js:17t.invoke @ polyfills.js:3inner.inner.fork.onInvoke @ main.js:3t.invoke @ polyfills.js:3e.runGuarded @ polyfills.js:3t.runGuarded @ main.js:3s @ main.js:17t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
keras.js:32 Warning: a promise was rejected with a non-error: [object XMLHttpRequestProgressEvent]
    at XMLHttpRequest.i.onerror (file:///android_asset/www/assets/keras.js:4:23486)
    at XMLHttpRequest.n [as _onerror] (file:///android_asset/www/build/polyfills.js:1:1189)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at Object.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/main.js:3:26135)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at XMLHttpRequest.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
From previous event:
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22912)
    at file:///android_asset/www/assets/keras.js:4:22656
    at Array.map (native)
    at t.l.value (file:///android_asset/www/assets/keras.js:4:22631)
    at new t (file:///android_asset/www/assets/keras.js:4:22286)
    at new t (file:///android_asset/www/build/main.js:12:13315)
    at new t (file:///android_asset/www/build/main.js:35:12930)
    at e.createInternal (file:///android_asset/www/build/main.js:35:13377)
    at e.t.create (file:///android_asset/www/build/main.js:2:7287)
    at t.create (file:///android_asset/www/build/main.js:2:4857)
    at e._viewInit (file:///android_asset/www/build/main.js:8:5217)
    at e._nextTrns (file:///android_asset/www/build/main.js:8:3336)
    at e._queueTrns (file:///android_asset/www/build/main.js:8:3111)
    at e._setPages (file:///android_asset/www/build/main.js:8:2230)
    at e.setRoot (file:///android_asset/www/build/main.js:8:2013)
    at t.openPage (file:///android_asset/www/build/main.js:12:1962)
    at e._handle_click_0_0 (file:///android_asset/www/build/main.js:31:28079)
    at file:///android_asset/www/build/main.js:10:19597
    at file:///android_asset/www/build/main.js:17:1516
keras.js:32 Unhandled rejection Error: predict() must take an object where the keys are the named inputs of the model: .
    at t.<anonymous> (file:///android_asset/www/assets/keras.js:4:28341)
    at o (file:///android_asset/www/assets/keras.js:44:2132)
    at s._invoke (file:///android_asset/www/assets/keras.js:44:3534)
    at s.t.(anonymous function) [as next] (file:///android_asset/www/assets/keras.js:44:2311)
From previous event:
    at t (file:///android_asset/www/assets/keras.js:4:28013)
    at t.deactivateDrawAndPredict (file:///android_asset/www/build/main.js:12:15770)
    at e._handle_touchend_18_5 (file:///android_asset/www/build/main.js:35:24387)
    at file:///android_asset/www/build/main.js:10:19597
    at file:///android_asset/www/build/main.js:17:1516
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13373)
    at e.runGuarded (file:///android_asset/www/build/polyfills.js:3:10997)
    at t.runGuarded (file:///android_asset/www/build/main.js:3:24648)
    at HTMLCanvasElement.s (file:///android_asset/www/build/main.js:17:1487)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at HTMLCanvasElement.invoke (file:///android_asset/www/build/polyfills.js:3:15164)
main.js:16 EXCEPTION: Failed to construct 'ImageData': The input data byte length is not a multiple of (4 * width).t.handleError @ main.js:16e.onError.subscribe.next @ main.js:9e.object.r @ main.js:16e.__tryOrUnsub @ main.js:30e.next @ main.js:30e._next @ main.js:30e.next @ main.js:30e.next @ main.js:11e.emit @ main.js:16t.triggerError @ main.js:3inner.inner.fork.onHandleError @ main.js:3t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3t.runGuarded @ main.js:3s @ main.js:17t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
main.js:16 ORIGINAL STACKTRACE:t.handleError @ main.js:16e.onError.subscribe.next @ main.js:9e.object.r @ main.js:16e.__tryOrUnsub @ main.js:30e.next @ main.js:30e._next @ main.js:30e.next @ main.js:30e.next @ main.js:11e.emit @ main.js:16t.triggerError @ main.js:3inner.inner.fork.onHandleError @ main.js:3t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3t.runGuarded @ main.js:3s @ main.js:17t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
main.js:16 Error: Failed to construct 'ImageData': The input data byte length is not a multiple of (4 * width).
    at Error (native)
    at o (file:///android_asset/www/build/main.js:12:12820)
    at t.deactivateDrawAndPredict (file:///android_asset/www/build/main.js:12:15150)
    at e._handle_touchend_18_5 (file:///android_asset/www/build/main.js:35:24387)
    at file:///android_asset/www/build/main.js:10:19597
    at file:///android_asset/www/build/main.js:17:1516
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13373)
    at e.runGuarded (file:///android_asset/www/build/polyfills.js:3:10997)
    at t.runGuarded (file:///android_asset/www/build/main.js:3:24648)
    at HTMLCanvasElement.s (file:///android_asset/www/build/main.js:17:1487)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at HTMLCanvasElement.invoke (file:///android_asset/www/build/polyfills.js:3:15164)t.handleError @ main.js:16e.onError.subscribe.next @ main.js:9e.object.r @ main.js:16e.__tryOrUnsub @ main.js:30e.next @ main.js:30e._next @ main.js:30e.next @ main.js:30e.next @ main.js:11e.emit @ main.js:16t.triggerError @ main.js:3inner.inner.fork.onHandleError @ main.js:3t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3t.runGuarded @ main.js:3s @ main.js:17t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3
polyfills.js:3 Uncaught IndexSizeError: Failed to construct 'ImageData': The input data byte length is not a multiple of (4 * width).e.runTask @ polyfills.js:3invoke @ polyfills.js:3
2keras.js:32 Unhandled rejection Error: predict() must take an object where the keys are the named inputs of the model: .
    at t.<anonymous> (file:///android_asset/www/assets/keras.js:4:28341)
    at o (file:///android_asset/www/assets/keras.js:44:2132)
    at s._invoke (file:///android_asset/www/assets/keras.js:44:3534)
    at s.t.(anonymous function) [as next] (file:///android_asset/www/assets/keras.js:44:2311)
From previous event:
    at t (file:///android_asset/www/assets/keras.js:4:28013)
    at t.deactivateDrawAndPredict (file:///android_asset/www/build/main.js:12:15770)
    at e._handle_touchend_18_5 (file:///android_asset/www/build/main.js:35:24387)
    at file:///android_asset/www/build/main.js:10:19597
    at file:///android_asset/www/build/main.js:17:1516
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13422)
    at Object.inner.inner.fork.onInvoke (file:///android_asset/www/build/main.js:3:26235)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:13373)
    at e.runGuarded (file:///android_asset/www/build/polyfills.js:3:10997)
    at t.runGuarded (file:///android_asset/www/build/main.js:3:24648)
    at HTMLCanvasElement.s (file:///android_asset/www/build/main.js:17:1487)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
    at HTMLCanvasElement.invoke (file:///android_asset/www/build/polyfills.js:3:15164)

sir, i got the above erorr when a image is taken with camera
........

**Comment by jose2007kj** [comment]
sir,@jhertzog..............now its working in browser,with image selection.......... 
but i am not getting results

**Comment by jhertzog** [comment]
I don't have a lot of time to devote to this but it looks like the NN file isn't getting copied to the `www` folder for some reason.  I have committed the `www` folder so if you re-pull you should have the files in the right place.

This was very rough prototyping work and I've only tested on iOS but it may work on Android as well.

**Comment by jose2007kj** [comment]
ok sir,thanks a lot.....
